doctrine:
    dbal:
        # La chaîne de connexion est définie dans votre variable d'environnement DATABASE_URL.
        # Par exemple, dans votre .env.local :
        # DATABASE_URL="postgresql://postgres.emxaygoqkbhmcxsqmsxj:[YOUR-PASSWORD]@aws-0-eu-central-1.pooler.supabase.com:6543/postgres?server_version=16&charset=utf8"
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '16'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        # Si vous utilisiez une fonction RAND pour MySQL, vous pouvez soit la remplacer par une fonction PostgreSQL, 
        # soit la supprimer si elle n'est pas utilisée.
        dql:
            numeric_functions:
                RAND: DoctrineExtensions\Query\Mysql\Rand


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" est généralement défini par ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
