framework:
    secret: '%env(APP_SECRET)%'
    session:
        enabled: true
        storage_factory_id: session.storage.factory.native
    serializer:
        default_context:
            enable_max_depth: true


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
