security:
    # Définition des password hashers (Symfony >=5.3)
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Définition des providers pour les utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Définition des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/ # Chemin pour les outils de dev
            security: false
        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login
                username_path: email
                password_path: password
        api:
            pattern: ^/api
            stateless: true
            security: false


    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Page d'accueil accessible à tous
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }        # Autres routes protégées


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4        # Valeur minimale pour bcrypt
                time_cost: 3   # Valeur minimale pour argon
                memory_cost: 10 # Valeur minimale pour argon
