# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            stateless: true
            provider: users
            json_login:
                check_path: /auth
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            
    access_control:
        - { path: ^/auth, roles: PUBLIC_ACCESS }  # Route d'authentification
        - { path: ^/register, roles: PUBLIC_ACCESS }  # Route d'inscription
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS } 
        - { path: ^/api/$, roles: PUBLIC_ACCESS }
        - { path: ^/docs, roles: PUBLIC_ACCESS }
        - {path: ^/api/artists/\d+/albums/\d+/songs/\d+$,roles: IS_AUTHENTICATED_FULLY,}
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
        



